DROP DATABASE IF EXISTS hectogon;

CREATE DATABASE hectogon;

USE hectogon;

CREATE TABLE User
(
Id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
Username VARCHAR(20) NOT NULL,
Password VARCHAR(64) NOT NULL,
Email VARCHAR(320) NOT NULL
);
