DROP DATABASE IF EXISTS hectogon;

CREATE DATABASE hectogon;

USE hectogon;

CREATE TABLE User
(
Id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
Username VARCHAR(20) NOT NULL,
Password VARCHAR(64) NOT NULL,
Email VARCHAR(320) NOT NULL,
RegisterDate TIMESTAMP NULL,
EmailConfirmed TIMESTAMP NULL
);

CREATE TABLE Login
(
UserId INT NOT NULL,
LoginTime TIMESTAMP NOT NULL,
FOREIGN KEY (UserId) REFERENCES User(Id)
);

CREATE TABLE Game
(
Id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
WinnerId INT NOT NULL,
TimeStarted TIMESTAMP NOT NULL,
TimeEnded TIMESTAMP NOT NULL,
FOREIGN KEY (WinnerId) REFERENCES User(Id)
);

CREATE TABLE User_Game
(
UserId INT NOT NULL,
GameId INT NOT NULL,
FOREIGN KEY (UserId) REFERENCES User(Id),
FOREIGN KEY (GameId) REFERENCES Game(Id)
);
